services:
  postgres:
    image: postgres:17
    container_name: quickcart-postgres-db
    environment:
      POSTGRES_USER: quickcart
      POSTGRES_PASSWORD: quickcart
      POSTGRES_DB: quickcart
    ports:
        - "5432:5432"