spring:
  application:
    name: QuickCart

  datasource:
    url: jdbc:postgresql://localhost:5432/quickcart
    username: quickcart
    password: quickcart

  mail:
    host: localhost
    port: 1025
    http:
      port: 8025

quickcart:
  mail:
    from: support@quickcart.com
  stripe:
    api-key: sk_test_51R4UxCP2acvI4IuRPfQLnaDzJyF89qzbRRdrnzCw2qvW6jigRxcVXDwkTd7eqaxmJbOPZO5smLpJ1Gn4UqBCFJx0005hAYauaD